/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouteSortRouteImport } from './routes/route-sort'
import { Route as RouteScanRouteImport } from './routes/route-scan'
import { Route as ReverseRouteImport } from './routes/reverse'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PasswordRouteImport } from './routes/password'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CodRouteImport } from './routes/cod'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StationIndexRouteImport } from './routes/station.index'
import { Route as InboundIndexRouteImport } from './routes/inbound.index'
import { Route as DeliveryIndexRouteImport } from './routes/delivery.index'
import { Route as StationReturnDepotRouteImport } from './routes/station.return-depot'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ListKindRouteImport } from './routes/list.$kind'
import { Route as InboundSortRouteImport } from './routes/inbound.sort'
import { Route as InboundCollectRouteImport } from './routes/inbound.collect'
import { Route as DeliveryMergeRouteImport } from './routes/delivery.merge'
import { Route as DeliveryCompleteRouteImport } from './routes/delivery.complete'
import { Route as ActionIdRouteImport } from './routes/action.$id'

const RouteSortRoute = RouteSortRouteImport.update({
  id: '/route-sort',
  path: '/route-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteScanRoute = RouteScanRouteImport.update({
  id: '/route-scan',
  path: '/route-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReverseRoute = ReverseRouteImport.update({
  id: '/reverse',
  path: '/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordRoute = PasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CodRoute = CodRouteImport.update({
  id: '/cod',
  path: '/cod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationIndexRoute = StationIndexRouteImport.update({
  id: '/station/',
  path: '/station/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundIndexRoute = InboundIndexRouteImport.update({
  id: '/inbound/',
  path: '/inbound/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryIndexRoute = DeliveryIndexRouteImport.update({
  id: '/delivery/',
  path: '/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const StationReturnDepotRoute = StationReturnDepotRouteImport.update({
  id: '/station/return-depot',
  path: '/station/return-depot',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListKindRoute = ListKindRouteImport.update({
  id: '/list/$kind',
  path: '/list/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundSortRoute = InboundSortRouteImport.update({
  id: '/inbound/sort',
  path: '/inbound/sort',
  getParentRoute: () => rootRouteImport,
} as any)
const InboundCollectRoute = InboundCollectRouteImport.update({
  id: '/inbound/collect',
  path: '/inbound/collect',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryMergeRoute = DeliveryMergeRouteImport.update({
  id: '/delivery/merge',
  path: '/delivery/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryCompleteRoute = DeliveryCompleteRouteImport.update({
  id: '/delivery/complete',
  path: '/delivery/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionIdRoute = ActionIdRouteImport.update({
  id: '/action/$id',
  path: '/action/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cod': typeof CodRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/password': typeof PasswordRoute
  '/pending': typeof PendingRoute
  '/reverse': typeof ReverseRoute
  '/route-scan': typeof RouteScanRoute
  '/route-sort': typeof RouteSortRoute
  '/action/$id': typeof ActionIdRoute
  '/delivery/complete': typeof DeliveryCompleteRoute
  '/delivery/merge': typeof DeliveryMergeRoute
  '/inbound/collect': typeof InboundCollectRoute
  '/inbound/sort': typeof InboundSortRoute
  '/list/$kind': typeof ListKindRoute
  '/order/$id': typeof OrderIdRoute
  '/station/return-depot': typeof StationReturnDepotRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/inbound/': typeof InboundIndexRoute
  '/station/': typeof StationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cod': typeof CodRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/password': typeof PasswordRoute
  '/pending': typeof PendingRoute
  '/reverse': typeof ReverseRoute
  '/route-scan': typeof RouteScanRoute
  '/route-sort': typeof RouteSortRoute
  '/action/$id': typeof ActionIdRoute
  '/delivery/complete': typeof DeliveryCompleteRoute
  '/delivery/merge': typeof DeliveryMergeRoute
  '/inbound/collect': typeof InboundCollectRoute
  '/inbound/sort': typeof InboundSortRoute
  '/list/$kind': typeof ListKindRoute
  '/order/$id': typeof OrderIdRoute
  '/station/return-depot': typeof StationReturnDepotRoute
  '/delivery': typeof DeliveryIndexRoute
  '/inbound': typeof InboundIndexRoute
  '/station': typeof StationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cod': typeof CodRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/password': typeof PasswordRoute
  '/pending': typeof PendingRoute
  '/reverse': typeof ReverseRoute
  '/route-scan': typeof RouteScanRoute
  '/route-sort': typeof RouteSortRoute
  '/action/$id': typeof ActionIdRoute
  '/delivery/complete': typeof DeliveryCompleteRoute
  '/delivery/merge': typeof DeliveryMergeRoute
  '/inbound/collect': typeof InboundCollectRoute
  '/inbound/sort': typeof InboundSortRoute
  '/list/$kind': typeof ListKindRoute
  '/order/$id': typeof OrderIdRoute
  '/station/return-depot': typeof StationReturnDepotRoute
  '/delivery/': typeof DeliveryIndexRoute
  '/inbound/': typeof InboundIndexRoute
  '/station/': typeof StationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cod'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/password'
    | '/pending'
    | '/reverse'
    | '/route-scan'
    | '/route-sort'
    | '/action/$id'
    | '/delivery/complete'
    | '/delivery/merge'
    | '/inbound/collect'
    | '/inbound/sort'
    | '/list/$kind'
    | '/order/$id'
    | '/station/return-depot'
    | '/delivery/'
    | '/inbound/'
    | '/station/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cod'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/password'
    | '/pending'
    | '/reverse'
    | '/route-scan'
    | '/route-sort'
    | '/action/$id'
    | '/delivery/complete'
    | '/delivery/merge'
    | '/inbound/collect'
    | '/inbound/sort'
    | '/list/$kind'
    | '/order/$id'
    | '/station/return-depot'
    | '/delivery'
    | '/inbound'
    | '/station'
  id:
    | '__root__'
    | '/'
    | '/cod'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/password'
    | '/pending'
    | '/reverse'
    | '/route-scan'
    | '/route-sort'
    | '/action/$id'
    | '/delivery/complete'
    | '/delivery/merge'
    | '/inbound/collect'
    | '/inbound/sort'
    | '/list/$kind'
    | '/order/$id'
    | '/station/return-depot'
    | '/delivery/'
    | '/inbound/'
    | '/station/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodRoute: typeof CodRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PasswordRoute: typeof PasswordRoute
  PendingRoute: typeof PendingRoute
  ReverseRoute: typeof ReverseRoute
  RouteScanRoute: typeof RouteScanRoute
  RouteSortRoute: typeof RouteSortRoute
  ActionIdRoute: typeof ActionIdRoute
  DeliveryCompleteRoute: typeof DeliveryCompleteRoute
  DeliveryMergeRoute: typeof DeliveryMergeRoute
  InboundCollectRoute: typeof InboundCollectRoute
  InboundSortRoute: typeof InboundSortRoute
  ListKindRoute: typeof ListKindRoute
  OrderIdRoute: typeof OrderIdRoute
  StationReturnDepotRoute: typeof StationReturnDepotRoute
  DeliveryIndexRoute: typeof DeliveryIndexRoute
  InboundIndexRoute: typeof InboundIndexRoute
  StationIndexRoute: typeof StationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/route-sort': {
      id: '/route-sort'
      path: '/route-sort'
      fullPath: '/route-sort'
      preLoaderRoute: typeof RouteSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-scan': {
      id: '/route-scan'
      path: '/route-scan'
      fullPath: '/route-scan'
      preLoaderRoute: typeof RouteScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reverse': {
      id: '/reverse'
      path: '/reverse'
      fullPath: '/reverse'
      preLoaderRoute: typeof ReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password': {
      id: '/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof PasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cod': {
      id: '/cod'
      path: '/cod'
      fullPath: '/cod'
      preLoaderRoute: typeof CodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/': {
      id: '/station/'
      path: '/station'
      fullPath: '/station/'
      preLoaderRoute: typeof StationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/': {
      id: '/inbound/'
      path: '/inbound'
      fullPath: '/inbound/'
      preLoaderRoute: typeof InboundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/': {
      id: '/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof DeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station/return-depot': {
      id: '/station/return-depot'
      path: '/station/return-depot'
      fullPath: '/station/return-depot'
      preLoaderRoute: typeof StationReturnDepotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$kind': {
      id: '/list/$kind'
      path: '/list/$kind'
      fullPath: '/list/$kind'
      preLoaderRoute: typeof ListKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/sort': {
      id: '/inbound/sort'
      path: '/inbound/sort'
      fullPath: '/inbound/sort'
      preLoaderRoute: typeof InboundSortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbound/collect': {
      id: '/inbound/collect'
      path: '/inbound/collect'
      fullPath: '/inbound/collect'
      preLoaderRoute: typeof InboundCollectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/merge': {
      id: '/delivery/merge'
      path: '/delivery/merge'
      fullPath: '/delivery/merge'
      preLoaderRoute: typeof DeliveryMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/complete': {
      id: '/delivery/complete'
      path: '/delivery/complete'
      fullPath: '/delivery/complete'
      preLoaderRoute: typeof DeliveryCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action/$id': {
      id: '/action/$id'
      path: '/action/$id'
      fullPath: '/action/$id'
      preLoaderRoute: typeof ActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodRoute: CodRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PasswordRoute: PasswordRoute,
  PendingRoute: PendingRoute,
  ReverseRoute: ReverseRoute,
  RouteScanRoute: RouteScanRoute,
  RouteSortRoute: RouteSortRoute,
  ActionIdRoute: ActionIdRoute,
  DeliveryCompleteRoute: DeliveryCompleteRoute,
  DeliveryMergeRoute: DeliveryMergeRoute,
  InboundCollectRoute: InboundCollectRoute,
  InboundSortRoute: InboundSortRoute,
  ListKindRoute: ListKindRoute,
  OrderIdRoute: OrderIdRoute,
  StationReturnDepotRoute: StationReturnDepotRoute,
  DeliveryIndexRoute: DeliveryIndexRoute,
  InboundIndexRoute: InboundIndexRoute,
  StationIndexRoute: StationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
